PHIWIKI/Models/dashboard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PHIWIKI.Models
{
    public class dashboard
    {
        public List<tbl_transaksi_buku> transaksi { get; set; }
        public List<View_orderbook> myorder { get; set; }
        public List<tbl_user> user { get; set; }
        public List<tbl_layanan_pengaduan> pengaduan { get; set; }
        public List<tbl_reimburse> reimburses { get; set; }
        public List<tbl_jawaban_quiz> quiz { get; set; }
        public List<tbl_timeline> timelines { get; set; }
    }
}

PHIWIKI/Controllers/admin/DashboardController.cs
using Newtonsoft.Json;
using PHIWIKI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;


namespace phiwiki.Controllers.Controller_Admin
{
    public class DashboardController : Controller
    {
        phiwikiEntities db = new phiwikiEntities();
        public ActionResult Dashboard()
        {

            string id = Session["role"].ToString();
            if (Session["username"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            else if (id == "1")
            {
                return RedirectToAction("Permission", "User");
            }
            else
            {

                List<tbl_transaksi_buku> order = db.tbl_transaksi_buku.ToList();
                List<tbl_user> costumer = db.tbl_user.ToList();
                List<tbl_layanan_pengaduan> complaint = db.tbl_layanan_pengaduan.ToList();
                List<tbl_reimburse> reimburses = db.tbl_reimburse.ToList();
                List<tbl_timeline> timeline = db.tbl_timeline.ToList();
                List<tbl_jawaban_quiz> quiz = db.tbl_jawaban_quiz.ToList();
                List<View_orderbook> myorder = db.View_orderbook.ToList();
                dashboard list = new dashboard();
                list.transaksi = order;
                list.user = costumer;
                list.pengaduan = complaint;
                list.reimburses = reimburses;
                list.timelines = timeline;
                list.quiz = quiz;
                list.myorder = myorder;
                return View(list);
            }


        }

        public JsonResult User()
        {
            var user = db.tbl_user.Where(x => x.fk_id_role == 1).Count();
            return Json(user, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Order()
        {
            var order = db.tbl_transaksi_buku.Select(x => x.id_transaksi_buku).Count();
            return Json(order, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Complaint()
        {
            var complaint = db.tbl_layanan_pengaduan.Select(x => x.id_layanan_pengaduan).Count();
            return Json(complaint, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Amount()
        {
            var amount = db.tbl_transaksi_buku.Select(x => x.harga_total).Sum().ToString("C0", CultureInfo.CreateSpecificCulture("id-ID"));
            return Json(amount, JsonRequestBehavior.AllowGet);
        }

    }
}

PHIWIKI/Views/Dashboard/Dashboard.cshtml
@model PHIWIKI.Models.dashboard
@using System.Globalization;

<div class="main-content">
    <div class="section_content section_content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="overview-wrap">
                        <h2 class="title-1">Dashboard</h2>
                    </div>
                </div>
            </div>
            <div class="row m-t-25">
                <div class="col-sm-6 col-lg-3">
                    <div class="statistic__item statistic__item--green">
                        <div class="overview__inner">
                            <div class="overview-box clearfix">
                                <div class="icon">
                                    <i class="zmdi zmdi-account-o"></i>
                                </div>
                                <div class="text" id="data">
                                    <h2>@Model.user.Where(x => x.fk_id_role == 1).Count()</h2>
                                </div>
                                </br>
                                <div class="text">
                                    <span>Costumer</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="statistic__item statistic__item--orange">
                        <div class="overview__inner">
                            <div class="overview-box clearfix">
                                <div class="icon">
                                    <i class="zmdi zmdi-shopping-cart"></i>
                                </div>
                                <div class="text" id="data2">
                                    <h2>@Model.transaksi.Select(x => x.id_transaksi_buku).Count()</h2>
                                </div>
                                </br>
                                <div class="text">
                                    <span>Books Order</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="statistic__item statistic__item--red">
                        <div class="overview__inner">
                            <div class="overview-box clearfix">
                                <div class="icon">
                                    <i class="zmdi zmdi-comment-alert"></i>
                                </div>
                                <div class="text" id="data3">
                                    <h2>@Model.pengaduan.Select(x => x.id_layanan_pengaduan).Count()</h2>
                                </div>
                                </br>
                                <div class="text">
                                    <span>Complaint</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="statistic__item statistic__item--blue">
                        <div class="overview__inner">
                            <div class="overview-box clearfix">
                                <div class="icon">
                                    <i class="zmdi zmdi-money"></i>
                                </div>
                                <div class="text" id="data4">
                                    <h2>@Model.transaksi.Select(x => x.harga_total).Sum().ToString("C0", CultureInfo.CreateSpecificCulture("id-ID"))</h2>
                                </div>
                                </br>
                                <div class="text">
                                    <span>total income</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="au-card au-card--no-shadow au-card--no-pad m-b-10">
                        <div class="au-card-title" style="background-image:url('images/bg-title-01.jpg');">
                            <div class="bg-overlay bg-overlay--blue"></div>
                            <h3>
                                <i class="zmdi zmdi-account-calendar"></i>TimeLine
                            </h3>
                        </div>
                        <div class="au-task js-list-load">
                            @foreach (var item in Model.timelines)
                            {
                                <div class="au-task_item au-task_item--warning">
                                    <div class="au-task__item-inner">
                                        <td>@item.divisi</td>
                                        <h5 class="task">
                                            <td>@item.jobdesc</td>
                                            <td class="text-right">(@item.progress)</td>
                                        </h5>
                                        <td>End Date</td>
                                        <span class="time">==>@item.end</span>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="au-card au-card--bg-blue au-card-top-countries m-b-40">
                        <div class="au-card-inner">
                            <div class="table-responsive">
                                <table class="table table-top-countries">
                                    <h2 class="title-1 m-b-25 text-white">Quiz Score</h2>
                                    <tbody>
                                        @foreach (var a in Model.quiz)
                                        {
                                            <tr>
                                                <td>@a.nama</td>
                                                <td class="text-right">@a.statusjawaban</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </br>
            <div class="row">
                <div class="col-lg-6">
                    <h2 class="title-1 m-b-10">Books Order</h2>
                    <div class="table-responsive table--no-card m-b-40">
                        <table class="table table-borderless table-striped table-earning">
                            <thead>
                                <tr>
                                    <th>Number</th>
                                    <th>name</th>
                                    <th class="text-right">Status</th>
                                    <th class="text-right">price</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{int number = 1; }
                                @foreach (var item in Model.myorder)
                                {
                                    <tr>
                                        <td>@number</td>
                                        <td>@item.nama_user</td>
                                        <td>@item.status</td>
                                        <td>@item.harga_total</td>
                                    </tr>
                                    number++;
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-lg-6">
                    <h2 class="title-1 m-b-10">Reimburse</h2>
                    <div class="table-responsive table--no-card m-b-30">
                        <table class="table table-borderless table-striped table-earning">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Division</th>
                                    <th class="text-right">price</th>
                                    <th class="text-right">Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{int num = 1; }
                                @foreach (var item in Model.reimburses)
                                {
                                    <tr>
                                        <td>@item.nama</td>
                                        <td>@item.divisi</td>
                                        <td>@item.total_pengeluaran</td>
                                        <td>@item.konfirmasi2</td>
                                    </tr>
                                    num++;
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function data() {
        $.ajax({
            url: "@Url.Action("User","Dashboard")",
            success: function (response) {
                if (response != null) {
                    $('#data').html('<h2>' + response + '</h2>');
                } else {
                    alert("Something Went Wrong!");
                }
            }
        });
    }
    function data2() {
        $.ajax({
            url: "@Url.Action("Order","Dashboard")",
            success: function (response) {
                if (response != null) {
                    $('#data2').html('<h2>' + response + '</h2>');
                } else {
                    alert("Something Went Wrong!");
                }
            }
        });
    }
    function data3() {
        $.ajax({
            url: "@Url.Action("Complaint","Dashboard")",
            success: function (response) {
                if (response != null) {
                    $('#data3').html('<h2>' + response + '</h2>');
                } else {
                    alert("Something Went Wrong!");
                }
            }
        });
    }
    function data4() {
        $.ajax({
            url: "@Url.Action("Amount","Dashboard")",
            success: function (response) {
                if (response != null) {
                    $('#data4').html('<h2>' + response + '</h2>');
                } else {
                    alert("Something Went Wrong!");
                }
            }
        });
    }
    setInterval(function () {
        data();
        data2();
        data3();
        data4();
    }, 5000);
</script>